#!bin/bash/


check_service() {

    service=$1
    action=$2

    if systemctl is-active --quiet "$service"
    then
        echo "$service is running"
    else
        echo "$service is not running"
        sudo systemctl "$action" "$service"
    fi
}

echo "Enter your service name:"
read service

echo "What should I do? start/stop/restart/status:"
read action

check_service "$service" "$action"









